### ISSUE TITLE
AssertionError: APEX and CUDA required for fused optimizers

### ISSUE THREAD

**Issue by DLT10010** [mahdi65/roadDamageDetection2020#2]
Using GPU training to report errors:  AssertionError: APEX and CUDA required for fused optimizers
How can I solve this problem

**Comment by sadransh** [comment]
Thank you for your interest in this repo, 


please check your CUDA driver is installed and also you PyTorch have access to Cuda. just open python in the terminal and enter this : 
```
import torch
torch.cuda.is_available() #should return True

````
otherwise, you should consider reinstalling PyTorch with respect to your Cuda version (refer to https://pytorch.org/) and/or Cuda.
 
for apex please refer to their repo https://github.com/NVIDIA/apex for installation. ( or refer to [readme](https://github.com/mahdi65/roadDamageDetection2020#usage) ) 
after installation you should see `apex 0.1` in `pip list`
